Feature/refactor users#19
CodelabUnifesp/PlaSMeDIS-API pull request #36
Opened 2021-07-26 16:46 UTC by Maegima

### O que esta pull request faz:

- [ ] Separa códigos presente no app.py em 4 módulos
    - [ ] Adiciona controller
    - [ ] Adiciona model
    - [ ] Adiciona service
    - [ ] Adiciona util
- [ ] Refatora /users/id:
    - [ ] Separa GET, PUT e DELETE
    - [ ] Corrige erro 500 no DELETE
    - [ ] Adiciona decorador json_required para verificar e retornar json
### Como testar:
`python3 app.py`

2021-07-26 16:59 UTC, Maegima commented
@dsalexan Além refatorar os endpoints /users/:id peguei pra separar o código no app.py em 1 módulo com 4 módulos filhos:
- api: Configuração do flask e conexão com bd
    - controller: Módulo para as rotas da api
    - model: Módulo para os modelos do banco de dados
    - service: Módulo onde fica a parte lógica para o tratamento dos endpoints
    - util: Módulo onde ficam funções e decoradores que auxiliam no tratamento dos endpoints
Ficou no app.py:
    - Registro das rotas
    - Inicialização da aplicação

2021-07-26 17:02 UTC, Maegima commented
Outras coisas que acho que seria bom colocar para refatoração é a padronização dos nomes dos endpoints e das funções para tratamento desses endpoints.

2021-07-27 11:45 UTC, dsalexan commented
@Maegima, eu criei uma branch separada (2.0) para servir como uma "master" das versões futuras (e a master que existe hoje fica como sendo a "versão atual de trabalho").

Eu ainda não revisei esse cara aqui ainda, mas recria esse pull request apontando pra 2.0 pra evitar um merge mt disruptivo na master

2021-07-27 11:46 UTC, dsalexan requested changes
@Maegima, eu criei uma branch separada (2.0) para servir como uma "master" das versões futuras (e a master que existe hoje fica como sendo a "versão atual de trabalho").

Eu ainda não revisei esse cara aqui ainda, mas recria esse pull request apontando pra 2.0 pra evitar um merge mt disruptivo na master

2021-07-27 16:41 UTC, Maegima commented
Movido para pr #39.

2021-07-27 16:41 UTC, closed without merging