Feature/documentation#21
CodelabUnifesp/PlaSMeDIS-API pull request #53
Opened 2021-09-07 21:04 UTC by Maegima

O que esta pull request faz:
- [ ] Adiciona base estrutural para a documentação dos endpoints
- [ ] documenta endpoints
    - [ ] /users/<id> GET
    - [ ]  /users/<id> PUT
    - [ ]  /users/<id> DELETE

Como testar:
python3 app.py

2021-09-12 06:36 UTC, dsalexan requested changes
Eu não dei uma olhada mt aprofundada pra ver o porque, mas a api não ta rodando com essas modificações. Eu chutaria que deve ser por causa do controller de users, mas é literalmente só um chute.

2021-09-12 23:37 UTC, Maegima commented
> Eu não dei uma olhada mt aprofundada pra ver o porque, mas a api não ta rodando com essas modificações. Eu chutaria que deve ser por causa do controller de users, mas é literalmente só um chute.

Que tipo de erro não tá nem executando? Ou é alguma rota que tá dando problema? Comigo tá funcionando, testei as rotas de do users.

2021-10-03 21:33 UTC, dsalexan approved these changes

2021-10-03 21:33 UTC, dsalexan commented on app.py
> +@app.route('/status')
O problema era especificamente com "/", então troquei o health check para "/status"

2021-10-03 21:33 UTC, dsalexan approved these changes

2021-10-03 21:33 UTC, merged